### ISSUE TITLE
Request error 403

### ISSUE THREAD

**Issue by thapld** [warren-bank/node-request-cli#1]
Hi,
I can make success request using postman but get 403 when request with node-request-cli

```
nget.cmd --url "https://livecdn.rumsport.com/stream/44/chunks.m3u8?token=6a1bb11840c6c163cb9dcef312c48131af1fa25e&is_vip=true&verify=1716093360-6xTnuOZ9gziQFZCxTUphkHEvDmMksKE%2Fps0MSV1lkRI%3D" --referer "https://live-streamfootball.com/" 
url: https://livecdn.rumsport.com/stream/44/chunks.m3u8?token=6a1bb11840c6c163cb9dcef312c48131af1fa25e
status code: 403
error: HTTP response status code: 403

'is_vip' is not recognized as an internal or external command,
operable program or batch file.
The syntax of the command is incorrect.
```
Please fix the problem.

**Comment by warren-bank** [comment]
in bash:

```bash
nget --url "https://livecdn.rumsport.com/stream/44/chunks.m3u8?token=6a1bb11840c6c163cb9dcef312c48131af1fa25e&is_vip=true&verify=1716093360-6xTnuOZ9gziQFZCxTUphkHEvDmMksKE%2Fps0MSV1lkRI%3D" --referer "https://live-streamfootball.com/"

# url: https://livecdn.rumsport.com/stream/44/chunks.m3u8?token=6a1bb11840c6c163cb9dcef312c48131af1fa25e&is_vip=true&verify=1716093360-6xTnuOZ9gziQFZCxTUphkHEvDmMksKE%2Fps0MSV1lkRI%3D
# status code: 403
# error: HTTP response status code: 403
```

```bash
curl -I -H "Referer: https://live-streamfootball.com/" "https://livecdn.rumsport.com/stream/44/chunks.m3u8?token=6a1bb11840c6c163cb9dcef312c48131af1fa25e&is_vip=true&verify=1716093360-6xTnuOZ9gziQFZCxTUphkHEvDmMksKE%2Fps0MSV1lkRI%3D"

# HTTP/2 403
```

in Windows cmd:

* the URL would need some encoding to escape `%` characters, so I'm not going to bother testing.. since it would ultimately produce the same result

in either case:

* I don't see why your terminal would see `&` in the quoted URL and split the line into 2 commands (ie: the 2nd starting with `is_vip`)
* since `curl` produces the same response status code, I don't see a problem..

**Comment by thapld** [comment]
I always get error when using your lib
![image](https://github.com/warren-bank/node-request-cli/assets/38736191/d44826c1-2968-4739-94c1-fd186a9e7fe2)

![image](https://github.com/warren-bank/node-request-cli/assets/38736191/09a0557b-ea84-4e6e-b3b7-4fd05d9780d0)

You can use this link will expire and will get 403 after 25 minute
https://livecdn.rumsport.com/stream/13/chunks.m3u8?token=6a1bb11840c6c163cb9dcef312c48131af1fa25e&is_vip=true&verify=1716127260-CuQkaFVRVLcArJwGFjNyqrMGekPLCRvVpuTZnW1b7QU%3D

Referer https://live-streamfootball.com/

**Comment by warren-bank** [comment]
Sorry, I missed the window of opportunity to use your link.

If `curl` is working and `nget` isn't.. then I only have 1 thought:

1. `curl` includes a default _User-Agent_ request header,
   whereas `nget` does not;
   it's very possible that your server rejects requests that don't include an agent..
   in which case you should test `nget` by adding one.

default:

```bash
curl "http://httpbin.org/headers"

# {
#   "headers": {
#     "Accept": "*/*",
#     "Host": "httpbin.org",
#     "User-Agent": "curl/7.58.0"
#   }
# }
```

```bash
nget --url "http://httpbin.org/headers" -O -

# {
#   "headers": {
#     "Accept-Encoding": "identity, gzip, deflate, br",
#     "Host": "httpbin.org"
#   }
# }
```

with explicit agent:

```bash
nget --url "http://httpbin.org/headers" --user-agent "nget/4.0.19" -O -

# {
#   "headers": {
#     "Accept-Encoding": "identity, gzip, deflate, br",
#     "Host": "httpbin.org",
#     "User-Agent": "nget/4.0.19"
#   }
# }
```

**Comment by warren-bank** [comment]
and..
if a missing _User-Agent_ is the cause for your issue..
both here, as well as in using _HLS Proxy_,
then I should quickly point out that:

```bash
hlsd --useragent "Chrome/125"
```

**Comment by thapld** [comment]
Thank you for your help. It works. And HLS-Proxy also work. I will close the ticket.
